### PR TITLE
Fix live reloading when modify Vagrant files

### LINKED ISSUE #177: Fix live reloading when modify files into Vagrant

### PR DESCRIPTION
**Pull request by iLeonelPerea**
closes #177 

changes proposed in the pull request:

- Remove warnings
- Add browsersync socket

@thetonymaster

### CODE REVIEW

File: src/middleware/sagas.js [hunk 1]
```diff
@@ -187,18 +187,21 @@ export function* getRepositoryAccess(userAccess) {
   try {
     const repositoryAccess = yield call(doRequestGetRepositoryAccess, userAccess.value.get('authorization'), userAccess.value.get('oauth_request'));
     yield put(actions.receiveRepositoryAccess(fromJS({
-        integration: repositoryAccess.callback
+        'integration': repositoryAccess.callback
       }))
     );
   }
-  catch(error) {
+  catch(error) {
```
Comment (thetonymaster) [inline src/middleware/sagas.js]: Remove trailing spaces

Comment (iLeonelPerea) [inline src/middleware/sagas.js]: done.
